/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Command */

#ifndef _Included_Command
#define _Included_Command
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Commands
 * Method:    stringFromJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Command_stringFromJni
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
