/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Command */

#ifndef _Included_Command
#define _Included_Command
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Command
 * Method:    handleCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Command_handleCommand
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
